# vim: ft=python expandtab
Import('env')
env_fc_arch= env.Clone()

env_fc_arch['PDB'] = 'fc-arch.pdb'

env_fc_arch.Append(CPPPATH=['#', '#src', '#../msvc'])

sources=Split("fc-arch.c")

env_fc_arch.ParseConfig('pkg-config libxml-2.0 --cflags --libs')
env_fc_arch.ParseConfig('pkg-config freetype2 --cflags --libs')
exe = env_fc_arch.Program('fc-arch', sources)
env_fc_arch.AddPostAction(exe, 'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;2')

env_fc_arch.Command('fcarch.h', ['fcarch.tmpl.h', 'SConscript', '#src\\fcint.h', '#config.h'], '''
    fc-arch\\fc-arch.exe x86 <$SOURCE > $TARGET ''')
env_fc_arch.Depends('fcarch.h', exe)
